### ISSUE TITLE
Don't use Webpack and Babel for Web Server and GraphQL Server

### ISSUE THREAD

**Issue by vslinko** [vslinko/ripster#32]
# TODO
- [ ] Web Server
  - [ ] Don't use Babel
  - [ ] Don't use Webpack
- [ ] GraphQL Server
  - [ ] Don't use Babel
  - [ ] Don't use Webpack
